import { boolean, index, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

const createdAt = () => timestamp("created_at", { withTimezone: true }).defaultNow().notNull();
export const runStatus = pgEnum("run_status", ["running", "degraded", "failed", "published"]);
export const snapshotStatus = pgEnum("snapshot_status", ["staged", "validated", "published", "superseded"]);

export const providers = pgTable("providers", { id: uuid("id").defaultRandom().primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), createdAt: createdAt() });
export const models = pgTable("models", { id: uuid("id").defaultRandom().primaryKey(), providerId: uuid("provider_id").notNull().references(() => providers.id), slug: text("slug").notNull().unique(), name: text("name").notNull(), createdAt: createdAt() });
export const modelVersions = pgTable("model_versions", { id: uuid("id").defaultRandom().primaryKey(), modelId: uuid("model_id").notNull().references(() => models.id), version: text("version").notNull(), contextLength: numeric("context_length").notNull(), isCurrent: boolean("is_current").default(true).notNull(), createdAt: createdAt() }, (table) => [uniqueIndex("model_versions_model_version").on(table.modelId, table.version)]);
export const modelAliases = pgTable("model_aliases", { id: uuid("id").defaultRandom().primaryKey(), sourceKey: text("source_key").notNull(), externalId: text("external_id").notNull(), modelVersionId: uuid("model_version_id").notNull().references(() => modelVersions.id), createdAt: createdAt() }, (table) => [uniqueIndex("model_aliases_source_external").on(table.sourceKey, table.externalId)]);
export const sources = pgTable("sources", { id: uuid("id").defaultRandom().primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), tier: text("tier").notNull(), homepageUrl: text("homepage_url").notNull(), createdAt: createdAt() });
export const pipelineRuns = pgTable("pipeline_runs", { id: uuid("id").primaryKey(), runDate: text("run_date").notNull().unique(), status: runStatus("status").notNull(), inputHash: text("input_hash"), errors: jsonb("errors").$type<string[]>().default([]).notNull(), createdAt: createdAt(), completedAt: timestamp("completed_at", { withTimezone: true }) });
export const sourceFetches = pgTable("source_fetches", { id: uuid("id").defaultRandom().primaryKey(), pipelineRunId: uuid("pipeline_run_id").notNull().references(() => pipelineRuns.id), sourceId: uuid("source_id").notNull().references(() => sources.id), fingerprint: text("fingerprint"), payload: jsonb("payload").notNull(), status: text("status").notNull(), fetchedAt: createdAt() });
export const rawObservations = pgTable("raw_observations", { id: uuid("id").defaultRandom().primaryKey(), pipelineRunId: uuid("pipeline_run_id").notNull().references(() => pipelineRuns.id), modelVersionId: uuid("model_version_id").notNull().references(() => modelVersions.id), metricKey: text("metric_key").notNull(), value: numeric("value").notNull(), sourceUrl: text("source_url").notNull(), observedAt: text("observed_at").notNull(), sourceFetchId: uuid("source_fetch_id").references(() => sourceFetches.id), createdAt: createdAt() }, (table) => [index("raw_observations_run_metric").on(table.pipelineRunId, table.metricKey)]);
export const normalizedMetricValues = pgTable("normalized_metric_values", { id: uuid("id").defaultRandom().primaryKey(), pipelineRunId: uuid("pipeline_run_id").notNull().references(() => pipelineRuns.id), modelVersionId: uuid("model_version_id").notNull().references(() => modelVersions.id), metricKey: text("metric_key").notNull(), normalizedValue: numeric("normalized_value").notNull(), methodVersion: text("method_version").notNull(), rawObservationId: uuid("raw_observation_id").notNull().references(() => rawObservations.id), createdAt: createdAt() }, (table) => [uniqueIndex("normalized_values_run_version_metric").on(table.pipelineRunId, table.modelVersionId, table.metricKey)]);
export const boardScores = pgTable("board_scores", { id: uuid("id").defaultRandom().primaryKey(), pipelineRunId: uuid("pipeline_run_id").notNull().references(() => pipelineRuns.id), modelVersionId: uuid("model_version_id").notNull().references(() => modelVersions.id), boardSlug: text("board_slug").notNull(), score: numeric("score").notNull(), coverage: numeric("coverage").notNull(), methodVersion: text("method_version").notNull(), breakdown: jsonb("breakdown").notNull(), createdAt: createdAt() }, (table) => [uniqueIndex("board_scores_run_version_board").on(table.pipelineRunId, table.modelVersionId, table.boardSlug)]);
export const rankingSnapshots = pgTable("ranking_snapshots", { id: uuid("id").defaultRandom().primaryKey(), pipelineRunId: uuid("pipeline_run_id").notNull().references(() => pipelineRuns.id), boardSlug: text("board_slug").notNull(), snapshotDate: text("snapshot_date").notNull(), methodVersion: text("method_version").notNull(), inputHash: text("input_hash").notNull(), status: snapshotStatus("status").notNull(), createdAt: createdAt() }, (table) => [uniqueIndex("ranking_snapshots_run_board").on(table.pipelineRunId, table.boardSlug)]);
export const rankingEntries = pgTable("ranking_entries", { id: uuid("id").defaultRandom().primaryKey(), snapshotId: uuid("snapshot_id").notNull().references(() => rankingSnapshots.id), modelVersionId: uuid("model_version_id").notNull().references(() => modelVersions.id), rank: numeric("rank").notNull(), value: numeric("value").notNull(), previousRank: numeric("previous_rank"), isNew: boolean("is_new").default(false).notNull(), createdAt: createdAt() }, (table) => [uniqueIndex("ranking_entries_snapshot_version").on(table.snapshotId, table.modelVersionId)]);
export const publishedPointers = pgTable("published_pointers", { boardSlug: text("board_slug").primaryKey(), snapshotId: uuid("snapshot_id").notNull().references(() => rankingSnapshots.id), updatedAt: createdAt() });
export const unmappedEntities = pgTable("unmapped_entities", { id: uuid("id").defaultRandom().primaryKey(), sourceKey: text("source_key").notNull(), externalId: text("external_id").notNull(), payload: jsonb("payload").notNull(), firstSeenRunId: uuid("first_seen_run_id").notNull().references(() => pipelineRuns.id), createdAt: createdAt() }, (table) => [uniqueIndex("unmapped_entities_source_external").on(table.sourceKey, table.externalId)]);
