import { SiteHeader } from "@/components/site-header";
import { axisDefinitions, metricAnchors, methodVersion } from "@/lib/scoring-method";
export default function MethodologyPage() {
  return <main className="shell subpage method-copy"><SiteHeader /><h1>점수는 어떻게 계산하나요?</h1>
    <section><h2>종합은 지능만의 순위가 아닙니다</h2><p>이 사이트의 종합 지수는 능력 평가에 작업 비용과 출력 속도를 더한 값입니다. Artificial Analysis의 Intelligence Index와도 다른 지수입니다. 점수 60이 정답률 60% 또는 실제 업무 성공 확률 60%를 뜻하지 않습니다.</p><p>현재 계산법은 {methodVersion}. 이전 스냅샷은 당시 계산법과 입력 자료를 보존합니다.</p></section>
    <section><h2>분야별 기본 비중</h2><table className="method-table"><caption className="sr-only">종합 지수의 기본 가중치와 평가 항목</caption><thead><tr><th scope="col">분야</th><th scope="col">비중</th><th scope="col">구성 평가</th></tr></thead><tbody>{Object.entries(axisDefinitions).map(([key,axis]) => <tr key={key}><th scope="row">{axis.label}</th><td>{axis.weight*100}%</td><td>{axis.metrics.join(", ")}</td></tr>)}</tbody></table><p>같은 분야 안에서는 확보한 평가값의 환산 점수를 동일 비중으로 평균합니다. 코딩·업무·한국어 순위는 해당 분야 평균만 사용합니다. 작업 비용과 속도는 각각 한 항목입니다.</p></section>
    <section><h2>0–100점으로 환산하는 기준</h2><p>높을수록 좋은 평가: <code>100 × (원점수 − 하한) / (상한 − 하한)</code>. 결과가 0보다 작으면 0, 100보다 크면 100으로 제한합니다. 날짜별 최고·최저 모델에 맞춰 기준을 바꾸지 않습니다.</p><ul><li>능력 평가: 하한 0, 상한 100. 소스가 0–1 비율로 제공한 항목은 수집 때 100을 곱합니다.</li><li>출력 속도: 하한 {metricAnchors.output_speed[0]}, 상한 {metricAnchors.output_speed[1]} 토큰/초.</li><li>작업 비용: <code>100 − 100 × 비용 / 8</code>, 0–100으로 제한. $0은 100점, $4는 50점, $8 이상은 0점입니다. 메인에는 이 지수 대신 실제 평가 작업당 USD 비용을 표시합니다.</li></ul><p>비용이 $8 이상인 모델들은 환산 지수가 모두 0이므로 순위상 동점 처리와 원비용의 크기는 다를 수 있습니다. 속도도 400 토큰/초 이상은 100점입니다.</p></section>
    <section><h2>없는 자료는 어떻게 처리하나요?</h2><p>없는 값은 0이나 임의 평균으로 채우지 않습니다. 축 안에 평가 하나라도 있으면 그 축을 사용합니다. 따라서 축 확보율 100%라도 그 안의 모든 벤치마크가 있다는 뜻은 아닙니다.</p><p>종합 순위에 들려면 확보한 축의 기본 비중 합이 50% 이상이고, 능력 분야(추론·코딩·업무·긴 문서·한국어) 중 두 분야 이상에 자료가 있어야 합니다. 개별 분야는 한 항목이라도 있으면 순위를 계산합니다. 한국어는 현재 자료가 없어 순위를 제공하지 않습니다.</p><p>종합 = <code>Σ(확보한 축 점수 × 기본 비중) / Σ(확보한 축 기본 비중)</code>. 상세 페이지에 표시하는 반영 비율은 이 재분배 이후의 비율입니다.</p><p>종합의 ‘평가 항목 확보율’은 확보한 축의 기본 비중 합입니다. 개별 분야에서는 해당 분야의 전체 항목 중 확보한 항목 비율입니다. 내부 기존 신뢰도 표시 기준은 80% 이상 ‘높음’, 55% 이상 ‘보통’, 나머지 ‘낮음’이었으나, 통계적 신뢰도나 공식 정보 검증률이 아니므로 화면에서는 확보율과 결측 항목을 직접 표시합니다.</p></section>
    <section><h2>계산 예시</h2><p>추론 80, 코딩 60, 업무 50, 비용 지수 50, 속도 지수 50만 확보했다면 기본 비중 합은 25+25+15+10+5 = 80%입니다.</p><p><code>(80×0.25 + 60×0.25 + 50×0.15 + 50×0.10 + 50×0.05) / 0.80 = 62.5</code>. 최종 비중은 추론·코딩 각각 31.25%, 업무 18.75%, 비용 12.5%, 속도 6.25%입니다.</p><p>표시는 소수 첫째 자리로 반올림하지만 정렬은 저장된 원래 점수로 합니다. 완전히 같은 점수는 해당 실행에서 자료를 읽은 순서를 유지해 서로 다른 순번을 부여합니다. 따라서 동점 순번을 성능 우열로 읽으면 안 됩니다. 평가 구성·관측일이 다른 모델의 작은 점수 차이도 신중히 해석하세요.</p></section>
    <section><h2>평가 작업 비용 ≠ API 요금 ≠ 구독료</h2><p>작업 비용은 Artificial Analysis가 Intelligence Index 평가 작업에서 관측한 USD/task입니다. 이 비용만 역환산한 지수이며, 성공 확률로 보정한 가성비나 Cost Per Successful Task가 아닙니다. 실제 업무에 필요한 호출 수·입출력 길이·재시도는 달라집니다.</p><p>API 단가는 입력·출력 100만 토큰당 가격이고, ChatGPT·Claude 같은 앱 구독료는 월 이용료입니다. 이 세 가격을 서로 대체하거나 혼합하지 않습니다. 공식 API 요금과 외부 제공업체 요금도 출처별로 구분합니다.</p></section>
    <section><h2>평가 등재와 공식 소개 검증은 별개입니다</h2><p>신뢰하는 평가 어댑터(현재 Artificial Analysis)는 새 평가 모델의 identity·version·alias를 만들 수 있습니다. 공개 순위의 기준을 통과하면 평가에 등재됩니다. 이는 개발사의 공식 이름·앱 제공·가격·라이선스를 검증했다는 뜻이 아닙니다.</p><p>다른 소스의 미매핑 모델은 승인·매핑 대기열에 남습니다. 소개 콘텐츠는 별도 계층에서 공식 자료를 검증한 후 공개합니다. 자료가 부족한 모델은 ‘공식 소개·이용 정보 확인 중’으로 표시합니다.</p></section>
    <section><h2>날짜와 갱신</h2><p>매일 00:00 KST에 수집을 시작합니다. 완료 시각은 다를 수 있으며 실시간 서비스가 아닙니다. 순위 기준 날짜, 원자료 관측일, 공식 소개 확인일은 서로 다른 날짜입니다. 현재 AA·OpenRouter 어댑터의 관측일은 원자료를 수집한 UTC 날짜입니다. 평가 시행일이나 개발사의 수정 시각을 뜻하지 않습니다. 날짜만 기록된 항목에 정확한 시각을 만들어 넣지 않습니다.</p><p>모든 분야의 새 순위를 검증한 뒤 한 번에 공개합니다. 실패하면 이전 공개 순위를 유지하고 같은 입력을 다시 실행해도 중복 공개하지 않습니다. 화면의 마지막 정상 생성 시각은 공개 포인터가 가리키는 실행에서 읽으며, 실패한 새 실행의 시각으로 바꾸지 않습니다.</p></section>
    <section><h2>사용하는 자료</h2><ul><li><a href="https://artificialanalysis.ai/leaderboards/models" target="_blank" rel="noreferrer">Artificial Analysis 모델 평가 ↗</a>: 능력·평가 작업 비용·출력 속도·지연. 평가 조건은 원문과 상세 페이지의 버전을 확인하세요.</li><li><a href="https://openrouter.ai/docs/api/api-reference/models/get-models" target="_blank" rel="noreferrer">OpenRouter Models API 문서 ↗</a>: 외부 제공 가격·컨텍스트 등 보조 관측값. 등록 사실만으로 공식 앱 제공을 판단하지 않습니다.</li><li>개발사 발표·문서·가격표·라이선스: 소개와 사용 경로의 근거. 모델별로 출처와 수동 확인일을 표시합니다.</li></ul></section>
  </main>;
}
