import Link from "next/link";
import { allBoards, latestSnapshot, movementSummary } from "@/lib/catalog";
import { BoardTable } from "@/components/board-table";
const formatDate = (date: string) => new Intl.DateTimeFormat("en", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`));

export default function Home() { const snapshot = latestSnapshot(); const movement = movementSummary(snapshot); const leaders = ["overall", "coding", "price"] as const; return <main className="shell">
  <header className="topbar"><Link href="/" className="brand">AI <span>LEADERBOARD</span></Link><nav aria-label="Primary navigation"><Link href="/boards">Boards</Link><Link href="/methodology">Methodology</Link></nav><time dateTime={snapshot.date} className="snapshot-date">Snapshot {formatDate(snapshot.date)}</time></header>
  <section className="intro" aria-labelledby="today-heading"><div><p className="eyebrow">DAILY AI SCOREBOARD</p><h1 id="today-heading">Today&apos;s AI landscape,<br /><em>with receipts.</em></h1></div><p className="intro-copy">Three lenses, 10 current model entries, and every score traceable to the reported raw result and source.</p></section>
  <section className="pulse" aria-label="Today’s changes"><div><strong>{movement.up}</strong><span>moved up</span></div><div><strong>{movement.down}</strong><span>moved down</span></div><div><strong>{movement.newModels}</strong><span>new entries</span></div><p>Rank movement compares this published snapshot with {formatDate(snapshot.previousDate)}.</p></section>
  <section className="leaders" aria-label="Leaderboard highlights">{leaders.map((slug) => { const board = snapshot.boards[slug]; const entry = board.entries[0]; return <Link className="leader-card" href={`/boards/${slug}`} key={slug}><span>{board.label}</span><strong>#{entry.rank}</strong><b>{entry.model.name}</b><small>{slug === "price" ? `$${entry.value.toFixed(2)} / 1M blended` : `${entry.value.toFixed(1)} score`}</small><i aria-hidden="true">↗</i></Link>; })}</section>
  <section className="section-head"><div><p className="eyebrow">THE CORE BOARDS</p><h2>See the ranking. See why.</h2></div><Link href="/boards" className="text-link">All boards <span>→</span></Link></section><div className="board-stack">{allBoards(snapshot).map((board) => <BoardTable board={board} key={board.slug} compact />)}</div>
  <aside className="method-callout"><p className="eyebrow">METHOD V1</p><h2>No black-box “AI score.”</h2><p>Rankings are deterministic: raw benchmark → fixed-anchor normalization → published board formula → daily snapshot.</p><Link href="/methodology">Read the methodology <span>→</span></Link></aside><footer>Curated source records · Deterministic ranking · Snapshot history preserved</footer>
</main>; }
