"use client";

import Link from "next/link";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ExternalLink } from "lucide-react";
import { latestModelComparison, latestModelComparisonSource } from "@/lib/latest-models";

export default function LatestModelChart() {
  return <section className="latest-model-panel" aria-labelledby="latest-model-title"><header><div><p>OFFICIAL SPECS · 2026-09-23</p><h2 id="latest-model-title">GPT-6 최신 모델 비교</h2></div><span>성능 순위가 아닌 공식 Standard API 단가 비교입니다.</span></header><div className="latest-model-grid"><div className="latest-chart" aria-label="GPT-6 모델별 입력 및 출력 토큰 가격 막대 차트"><ResponsiveContainer width="100%" height="100%"><BarChart data={latestModelComparison} layout="vertical" margin={{ top: 4, right: 18, bottom: 4, left: 8 }}><CartesianGrid stroke="#20304C" strokeDasharray="3 3" horizontal={false} /><XAxis type="number" tick={{ fill: "#8FA1BD", fontSize: 9 }} unit="$" /><YAxis type="category" dataKey="name" width={92} tick={{ fill: "#C7D3E5", fontSize: 10 }} /><Tooltip contentStyle={{ background: "#111B31", border: "1px solid #30466D", borderRadius: 9, fontSize: 11 }} formatter={(value, name) => [`$${Number(value).toFixed(2)} / 1M`, name === "inputPrice" ? "입력" : "출력"]} /><Bar dataKey="inputPrice" name="입력" radius={[0, 4, 4, 0]}>{latestModelComparison.map((item) => <Cell key={`input-${item.slug}`} fill={item.color} opacity={.55} />)}</Bar><Bar dataKey="outputPrice" name="출력" radius={[0, 4, 4, 0]}>{latestModelComparison.map((item) => <Cell key={`output-${item.slug}`} fill={item.color} />)}</Bar></BarChart></ResponsiveContainer></div><div className="latest-model-list">{latestModelComparison.map((item) => <Link href={`/models/${item.slug}`} key={item.slug}><i style={{ background: item.color }} /><span><b>{item.name}</b><small>{item.role} · {(item.context / 1_000_000).toFixed(2)}M context</small></span><strong>${item.inputPrice} / ${item.outputPrice}</strong></Link>)}<a className="latest-source" href={latestModelComparisonSource.url} target="_blank" rel="noreferrer">{latestModelComparisonSource.label} · 확인 {latestModelComparisonSource.observedAt}<ExternalLink size={12} /></a></div></div></section>;
}
